import { ExpedienteServicio } from './types';

const today = new Date().toISOString().split('T')[0];

export const MOCK_EXPEDIENTES: ExpedienteServicio[] = [
  {
    id: 1,
    appointment_id: 'AP001',
    appointment_name: `Instalaciones ${today}`,
    work_order_id: 'WO001',
    work_order_name: 'Instalación Unidad 101',
    service_type: 'Instalación',
    installation_details: 'Din1: Ignición, Dout1: Paro de motor, Dout2: Buzzer, Din2: Botón de pánico',
    asset_name: 'Unidad 101',
    company_name: 'Transportes del Norte',
    client_name: 'Juan Pérez',
    technician_name: 'Carlos Martínez',
    technician_phone: '555-0101',
    email_tecnico: 'carlos.martinez@example.com',
    server_name: 'TVC',
    platform_number: 'P001',
    service_street: 'Av. Insurgentes 1234',
    service_city: 'Ciudad de México',
    service_state: 'CDMX',
    service_zip_code: '03100',
    service_latitude: 19.432608,
    service_longitude: -99.133209,
    status: 'PENDIENTE',
    scheduled_start_time: `${today}T09:00:00`,
    scheduled_end_time: `${today}T11:00:00`,
    device_esn: '',
    vehicle_license_plate: null,
    vehicle_vin: null,
    vehicle_brand: null,
    vehicle_model: null,
    vehicle_year: null,
    vehicle_color: null,
    vehicle_odometer: null,
    validation_start_timestamp: null,
    validation_end_timestamp: null,
    validation_summary_json: null,
    validation_final_status: null,
    created_at: `${today}T08:00:00`,
    updated_at: `${today}T08:00:00`
  },
  {
    id: 2,
    appointment_id: 'AP001',
    appointment_name: `Instalaciones ${today}`,
    work_order_id: 'WO002',
    work_order_name: 'Instalación Unidad 102',
    service_type: 'Instalación',
    installation_details: 'Din1: Ignición, Dout1: Paro de motor, Buzzer: Activado',
    asset_name: 'Unidad 102',
    company_name: 'Transportes del Norte',
    client_name: 'María López',
    technician_name: 'Carlos Martínez',
    technician_phone: '555-0101',
    email_tecnico: 'carlos.martinez@example.com',
    server_name: 'TCV S1',
    platform_number: 'P002',
    service_street: 'Calle Reforma 567',
    service_city: 'Guadalajara',
    service_state: 'Jalisco',
    service_zip_code: '44100',
    service_latitude: 20.659699,
    service_longitude: -103.349609,
    status: 'PENDIENTE',
    scheduled_start_time: `${today}T11:00:00`,
    scheduled_end_time: `${today}T13:00:00`,
    device_esn: '',
    vehicle_license_plate: null,
    vehicle_vin: null,
    vehicle_brand: null,
    vehicle_model: null,
    vehicle_year: null,
    vehicle_color: null,
    vehicle_odometer: null,
    validation_start_timestamp: null,
    validation_end_timestamp: null,
    validation_summary_json: null,
    validation_final_status: null,
    created_at: `${today}T08:00:00`,
    updated_at: `${today}T08:00:00`
  },
  {
    id: 3,
    appointment_id: 'AP002',
    appointment_name: `Mantenimiento ${today}`,
    work_order_id: 'WO003',
    work_order_name: 'Mantenimiento Unidad 201',
    service_type: 'Mantenimiento',
    installation_details: 'Din1: Ignición, Dout1: Paro de motor, Dout2: Buzzer, Din2: Botón de pánico',
    asset_name: 'Unidad 201',
    company_name: 'Logística Express',
    client_name: 'Roberto Sánchez',
    technician_name: 'Ana García',
    technician_phone: '555-0202',
    email_tecnico: 'ana.garcia@example.com',
    server_name: 'TCV S2',
    platform_number: 'P003',
    service_street: 'Boulevard Miguel Hidalgo 890',
    service_city: 'Monterrey',
    service_state: 'Nuevo León',
    service_zip_code: '64000',
    service_latitude: 25.686613,
    service_longitude: -100.316116,
    status: 'PENDIENTE',
    scheduled_start_time: `${today}T14:00:00`,
    scheduled_end_time: `${today}T16:00:00`,
    device_esn: '',
    vehicle_license_plate: null,
    vehicle_vin: null,
    vehicle_brand: null,
    vehicle_model: null,
    vehicle_year: null,
    vehicle_color: null,
    vehicle_odometer: null,
    validation_start_timestamp: null,
    validation_end_timestamp: null,
    validation_summary_json: null,
    validation_final_status: null,
    created_at: `${today}T08:00:00`,
    updated_at: `${today}T08:00:00`
  },
  {
    id: 4,
    appointment_id: 'AP002',
    appointment_name: `Mantenimiento ${today}`,
    work_order_id: 'WO004',
    work_order_name: 'Mantenimiento Unidad 202',
    service_type: 'Mantenimiento',
    installation_details: 'Ignición: Conectado, Paro de motor: Configurado, Buzzer instalado',
    asset_name: 'Unidad 202',
    company_name: 'Logística Express',
    client_name: 'Laura Ramírez',
    technician_name: 'Ana García',
    technician_phone: '555-0202',
    email_tecnico: 'ana.garcia@example.com',
    server_name: 'TVC',
    platform_number: 'P004',
    service_street: 'Av. Juárez 345',
    service_city: 'Querétaro',
    service_state: 'Querétaro',
    service_zip_code: '76000',
    service_latitude: 20.588793,
    service_longitude: -100.389888,
    status: 'PENDIENTE',
    scheduled_start_time: `${today}T16:00:00`,
    scheduled_end_time: `${today}T18:00:00`,
    device_esn: '',
    vehicle_license_plate: null,
    vehicle_vin: null,
    vehicle_brand: null,
    vehicle_model: null,
    vehicle_year: null,
    vehicle_color: null,
    vehicle_odometer: null,
    validation_start_timestamp: null,
    validation_end_timestamp: null,
    validation_summary_json: null,
    validation_final_status: null,
    created_at: `${today}T08:00:00`,
    updated_at: `${today}T08:00:00`
  },
  {
    id: 5,
    appointment_id: 'AP003',
    appointment_name: `Reparaciones ${today}`,
    work_order_id: 'WO005',
    work_order_name: 'Reparación Unidad 301',
    service_type: 'Reparación',
    installation_details: 'Din1: Ignición, Dout1: Paro de motor, Din2: Botón de pánico',
    asset_name: 'Unidad 301',
    company_name: 'Transporte Seguro',
    client_name: 'Pedro González',
    technician_name: 'Luis Hernández',
    technician_phone: '555-0303',
    email_tecnico: 'luis.hernandez@example.com',
    server_name: 'TCV S1',
    platform_number: 'P005',
    service_street: 'Calle Morelos 678',
    service_city: 'Puebla',
    service_state: 'Puebla',
    service_zip_code: '72000',
    service_latitude: 19.041297,
    service_longitude: -98.206291,
    status: 'PENDIENTE',
    scheduled_start_time: `${today}T08:00:00`,
    scheduled_end_time: `${today}T10:00:00`,
    device_esn: '',
    vehicle_license_plate: null,
    vehicle_vin: null,
    vehicle_brand: null,
    vehicle_model: null,
    vehicle_year: null,
    vehicle_color: null,
    vehicle_odometer: null,
    validation_start_timestamp: null,
    validation_end_timestamp: null,
    validation_summary_json: null,
    validation_final_status: null,
    created_at: `${today}T08:00:00`,
    updated_at: `${today}T08:00:00`
  },
  {
    id: 6,
    appointment_id: 'AP003',
    appointment_name: `Reparaciones ${today}`,
    work_order_id: 'WO006',
    work_order_name: 'Reparación Unidad 302',
    service_type: 'Reparación',
    installation_details: 'Ignición, Paro de motor, Buzzer, Botón de pánico',
    asset_name: 'Unidad 302',
    company_name: 'Transporte Seguro',
    client_name: 'Sofía Torres',
    technician_name: 'Luis Hernández',
    technician_phone: '555-0303',
    email_tecnico: 'luis.hernandez@example.com',
    server_name: 'TCV S2',
    platform_number: 'P006',
    service_street: 'Av. Constitución 123',
    service_city: 'Tijuana',
    service_state: 'Baja California',
    service_zip_code: '22000',
    service_latitude: 32.514948,
    service_longitude: -117.038208,
    status: 'PENDIENTE',
    scheduled_start_time: `${today}T10:00:00`,
    scheduled_end_time: `${today}T12:00:00`,
    device_esn: '',
    vehicle_license_plate: null,
    vehicle_vin: null,
    vehicle_brand: null,
    vehicle_model: null,
    vehicle_year: null,
    vehicle_color: null,
    vehicle_odometer: null,
    validation_start_timestamp: null,
    validation_end_timestamp: null,
    validation_summary_json: null,
    validation_final_status: null,
    created_at: `${today}T08:00:00`,
    updated_at: `${today}T08:00:00`
  }
];
