/*
  # Crear catálogos de marcas y modelos de vehículos

  1. Nuevas Tablas
    - `vehicle_brands` - Catálogo de marcas de vehículos
      - `id` (bigint, primary key, auto-increment)
      - `name` (text, unique) - Nombre de la marca en MAYÚSCULAS
      - `active` (boolean) - Si la marca está activa
      - `created_at` (timestamptz)
      
    - `vehicle_models` - Catálogo de modelos de vehículos
      - `id` (bigint, primary key, auto-increment)
      - `brand_id` (bigint, foreign key) - Relación con vehicle_brands
      - `name` (text) - Nombre del modelo en MAYÚSCULAS
      - `active` (boolean) - Si el modelo está activo
      - `created_at` (timestamptz)
      - UNIQUE(brand_id, name) - No duplicar modelos por marca

  2. Datos Iniciales
    - Se insertan las marcas principales de vehículos en México
    - Se insertan modelos populares para cada marca

  3. Seguridad
    - RLS habilitado en ambas tablas
    - Usuarios autenticados pueden leer los catálogos
    - Solo admins pueden modificar los catálogos
*/

-- Crear tabla de marcas
CREATE TABLE IF NOT EXISTS vehicle_brands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Crear tabla de modelos
CREATE TABLE IF NOT EXISTS vehicle_models (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_id BIGINT NOT NULL REFERENCES vehicle_brands(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  active BOOLEAN DEFAULT true NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  UNIQUE(brand_id, name)
);

-- Crear índices para mejorar el rendimiento
CREATE INDEX IF NOT EXISTS idx_vehicle_models_brand_id ON vehicle_models(brand_id);
CREATE INDEX IF NOT EXISTS idx_vehicle_brands_active ON vehicle_brands(active) WHERE active = true;
CREATE INDEX IF NOT EXISTS idx_vehicle_models_active ON vehicle_models(active) WHERE active = true;

-- Habilitar RLS
ALTER TABLE vehicle_brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE vehicle_models ENABLE ROW LEVEL SECURITY;

-- Políticas RLS: Todos pueden leer, solo admins pueden modificar
CREATE POLICY "Anyone can read vehicle brands"
  ON vehicle_brands FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Anyone can read vehicle models"
  ON vehicle_models FOR SELECT
  TO authenticated
  USING (true);

-- Insertar marcas principales
INSERT INTO vehicle_brands (name) VALUES
  ('VOLKSWAGEN'),
  ('NISSAN'),
  ('CHEVROLET'),
  ('FORD'),
  ('TOYOTA'),
  ('HONDA'),
  ('MAZDA'),
  ('KIA'),
  ('HYUNDAI'),
  ('JEEP'),
  ('RAM'),
  ('GMC'),
  ('DODGE'),
  ('CHRYSLER'),
  ('SEAT'),
  ('AUDI'),
  ('BMW'),
  ('MERCEDES-BENZ'),
  ('SUZUKI'),
  ('MITSUBISHI'),
  ('PEUGEOT'),
  ('RENAULT'),
  ('FIAT'),
  ('SUBARU'),
  ('ISUZU')
ON CONFLICT (name) DO NOTHING;

-- Insertar modelos populares para Volkswagen
INSERT INTO vehicle_models (brand_id, name)
SELECT id, modelo FROM vehicle_brands, (VALUES
  ('GOL'),
  ('JETTA'),
  ('VENTO'),
  ('TIGUAN'),
  ('TAOS'),
  ('POLO'),
  ('PASSAT'),
  ('BEETLE'),
  ('GOLF'),
  ('AMAROK'),
  ('SAVEIRO'),
  ('VIRTUS'),
  ('T-CROSS'),
  ('NIVUS')
) AS models(modelo)
WHERE vehicle_brands.name = 'VOLKSWAGEN'
ON CONFLICT (brand_id, name) DO NOTHING;

-- Insertar modelos populares para Nissan
INSERT INTO vehicle_models (brand_id, name)
SELECT id, modelo FROM vehicle_brands, (VALUES
  ('VERSA'),
  ('SENTRA'),
  ('ALTIMA'),
  ('KICKS'),
  ('X-TRAIL'),
  ('FRONTIER'),
  ('NP300'),
  ('MARCH'),
  ('NOTE'),
  ('PATHFINDER'),
  ('MURANO'),
  ('ROGUE'),
  ('MAXIMA'),
  ('370Z'),
  ('GT-R')
) AS models(modelo)
WHERE vehicle_brands.name = 'NISSAN'
ON CONFLICT (brand_id, name) DO NOTHING;

-- Insertar modelos populares para Chevrolet
INSERT INTO vehicle_models (brand_id, name)
SELECT id, modelo FROM vehicle_brands, (VALUES
  ('AVEO'),
  ('BEAT'),
  ('CAVALIER'),
  ('ONIX'),
  ('SPARK'),
  ('CRUZE'),
  ('MALIBU'),
  ('CAMARO'),
  ('CORVETTE'),
  ('TRAX'),
  ('TRACKER'),
  ('EQUINOX'),
  ('TRAVERSE'),
  ('TAHOE'),
  ('SUBURBAN'),
  ('SILVERADO'),
  ('CHEYENNE'),
  ('COLORADO'),
  ('TORNADO')
) AS models(modelo)
WHERE vehicle_brands.name = 'CHEVROLET'
ON CONFLICT (brand_id, name) DO NOTHING;

-- Insertar modelos populares para Ford
INSERT INTO vehicle_models (brand_id, name)
SELECT id, modelo FROM vehicle_brands, (VALUES
  ('FIESTA'),
  ('FIGO'),
  ('FOCUS'),
  ('FUSION'),
  ('MUSTANG'),
  ('ESCAPE'),
  ('BRONCO'),
  ('BRONCO SPORT'),
  ('EXPLORER'),
  ('EXPEDITION'),
  ('F-150'),
  ('RANGER'),
  ('TRANSIT'),
  ('LOBO'),
  ('EDGE')
) AS models(modelo)
WHERE vehicle_brands.name = 'FORD'
ON CONFLICT (brand_id, name) DO NOTHING;

-- Insertar modelos populares para Toyota
INSERT INTO vehicle_models (brand_id, name)
SELECT id, modelo FROM vehicle_brands, (VALUES
  ('YARIS'),
  ('COROLLA'),
  ('CAMRY'),
  ('PRIUS'),
  ('RAV4'),
  ('HIGHLANDER'),
  ('4RUNNER'),
  ('TACOMA'),
  ('TUNDRA'),
  ('HILUX'),
  ('AVANZA'),
  ('RUSH'),
  ('C-HR'),
  ('VENZA'),
  ('SEQUOIA')
) AS models(modelo)
WHERE vehicle_brands.name = 'TOYOTA'
ON CONFLICT (brand_id, name) DO NOTHING;

-- Insertar modelos populares para Honda
INSERT INTO vehicle_models (brand_id, name)
SELECT id, modelo FROM vehicle_brands, (VALUES
  ('CITY'),
  ('CIVIC'),
  ('ACCORD'),
  ('FIT'),
  ('HR-V'),
  ('CR-V'),
  ('PILOT'),
  ('ODYSSEY'),
  ('RIDGELINE'),
  ('INSIGHT'),
  ('PASSPORT')
) AS models(modelo)
WHERE vehicle_brands.name = 'HONDA'
ON CONFLICT (brand_id, name) DO NOTHING;

-- Insertar modelos populares para Mazda
INSERT INTO vehicle_models (brand_id, name)
SELECT id, modelo FROM vehicle_brands, (VALUES
  ('MAZDA2'),
  ('MAZDA3'),
  ('MAZDA6'),
  ('CX-3'),
  ('CX-30'),
  ('CX-5'),
  ('CX-9'),
  ('CX-50'),
  ('MX-5')
) AS models(modelo)
WHERE vehicle_brands.name = 'MAZDA'
ON CONFLICT (brand_id, name) DO NOTHING;

-- Insertar modelos populares para KIA
INSERT INTO vehicle_models (brand_id, name)
SELECT id, modelo FROM vehicle_brands, (VALUES
  ('RIO'),
  ('FORTE'),
  ('K5'),
  ('STINGER'),
  ('SOUL'),
  ('SELTOS'),
  ('SPORTAGE'),
  ('SORENTO'),
  ('TELLURIDE'),
  ('CARNIVAL'),
  ('NIRO'),
  ('EV6')
) AS models(modelo)
WHERE vehicle_brands.name = 'KIA'
ON CONFLICT (brand_id, name) DO NOTHING;

-- Insertar modelos populares para Hyundai
INSERT INTO vehicle_models (brand_id, name)
SELECT id, modelo FROM vehicle_brands, (VALUES
  ('ACCENT'),
  ('ELANTRA'),
  ('SONATA'),
  ('VENUE'),
  ('CRETA'),
  ('KONA'),
  ('TUCSON'),
  ('SANTA FE'),
  ('PALISADE'),
  ('IONIQ'),
  ('VELOSTER')
) AS models(modelo)
WHERE vehicle_brands.name = 'HYUNDAI'
ON CONFLICT (brand_id, name) DO NOTHING;
