/*
  # Create device_test_sessions table

  ## Purpose
  Store the current state of device testing sessions to maintain progress across page reloads
  and optimize query usage by tracking which tests have already been completed.

  ## Tables Created
  
  ### `device_test_sessions`
  Stores the current state of all device tests for a given service order.
  
  **Columns:**
  - `id` (bigint, primary key): Auto-incrementing unique identifier
  - `expediente_id` (text, unique): Composite ID from work_order_name + appointment_name (format: WOXXXXX-AP-XXXXX)
  - `esn` (text): Electronic Serial Number of the device being tested
  - `ignicion_exitosa` (boolean): Whether ignition test passed
  - `boton_exitoso` (boolean): Whether panic button test passed
  - `ubicacion_exitosa` (boolean): Whether location test passed
  - `bloqueo_exitoso` (boolean): Whether engine lock test passed
  - `buzzer_exitoso` (boolean): Whether buzzer test passed
  - `boton_fecha_preguntada` (text): Last date asked for panic button validation
  - `ubicacion_fecha_preguntada` (text): Last date asked for location validation
  - `url_ubicacion` (text): Google Maps URL for location validation
  - `intentos_realizados` (integer): Number of polling attempts made (max 10)
  - `session_active` (boolean): Whether the session is currently active
  - `last_query_at` (timestamptz): Timestamp of last device query
  - `created_at` (timestamptz): Session creation timestamp
  - `updated_at` (timestamptz): Last update timestamp

  ## Security
  - RLS enabled on `device_test_sessions` table
  - Public read/write access for now (can be restricted later based on auth requirements)

  ## Indexes
  - Unique index on `expediente_id` for fast lookups
  - Index on `esn` for device-based queries
  - Index on `session_active` for filtering active sessions
*/

-- Create device_test_sessions table
CREATE TABLE IF NOT EXISTS device_test_sessions (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  expediente_id text UNIQUE NOT NULL,
  esn text,
  ignicion_exitosa boolean DEFAULT false,
  boton_exitoso boolean DEFAULT false,
  ubicacion_exitosa boolean DEFAULT false,
  bloqueo_exitoso boolean DEFAULT false,
  buzzer_exitoso boolean DEFAULT false,
  boton_fecha_preguntada text,
  ubicacion_fecha_preguntada text,
  url_ubicacion text,
  intentos_realizados integer DEFAULT 0,
  session_active boolean DEFAULT true,
  last_query_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Create indexes for optimized queries
CREATE INDEX IF NOT EXISTS idx_device_test_sessions_esn 
  ON device_test_sessions(esn);

CREATE INDEX IF NOT EXISTS idx_device_test_sessions_active 
  ON device_test_sessions(session_active) 
  WHERE session_active = true;

CREATE INDEX IF NOT EXISTS idx_device_test_sessions_updated_at 
  ON device_test_sessions(updated_at);

-- Enable Row Level Security
ALTER TABLE device_test_sessions ENABLE ROW LEVEL SECURITY;

-- Create policies for public access
CREATE POLICY "Allow public read access to device_test_sessions"
  ON device_test_sessions
  FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Allow public insert access to device_test_sessions"
  ON device_test_sessions
  FOR INSERT
  TO public
  WITH CHECK (true);

CREATE POLICY "Allow public update access to device_test_sessions"
  ON device_test_sessions
  FOR UPDATE
  TO public
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow public delete access to device_test_sessions"
  ON device_test_sessions
  FOR DELETE
  TO public
  USING (true);

-- Create function to auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_device_test_sessions_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger to auto-update updated_at
CREATE TRIGGER update_device_test_sessions_timestamp
  BEFORE UPDATE ON device_test_sessions
  FOR EACH ROW
  EXECUTE FUNCTION update_device_test_sessions_updated_at();