/*
  # Add Prefolio System

  ## Purpose
  Add support for pre-service form (PREFOLIO) that technicians must complete
  before starting device tests. This includes vehicle data, equipment details,
  and photo documentation.

  ## Changes to Existing Tables

  ### `expedientes_servicio`
  Add new columns for prefolio data:
  - `prefolio_realizado` (boolean) - Whether prefolio has been completed
  - `prefolio_vehiculo_texto` (text) - Free text vehicle description
  - `vehicle_numero_economico` (text) - Economic number (optional)
  - `prefolio_modelo_dispositivo` (text) - Device model installed/reviewed
  - `prefolio_imei_dispositivo` (text) - Device IMEI
  - `prefolio_telefono_sim` (text) - SIM phone number

  Note: Reusing existing vehicle_* fields for brand, model, year, color, VIN,
  odometer, and license_plate. Also reusing device_esn and tipo_de_acta.

  ## New Tables

  ### `prefolio_fotos`
  Stores metadata for prefolio photos uploaded to Supabase Storage.

  **Columns:**
  - `id` (bigint, primary key) - Auto-incrementing unique identifier
  - `expediente_id` (bigint, foreign key) - Reference to expedientes_servicio
  - `campo` (text) - Field name (e.g., 'foto_vehiculo_frente', 'foto_odometro')
  - `file_path` (text) - Path in Supabase Storage bucket
  - `created_at` (timestamptz) - Upload timestamp
  - `created_by` (uuid) - User who uploaded (references auth.users)

  ## Security
  - RLS enabled on `prefolio_fotos` table
  - Public read/write for now (can be restricted later based on auth)

  ## Storage Bucket
  IMPORTANT: Must be created manually in Supabase Dashboard:
  - Bucket name: `prefolio-photos`
  - Public: false
  - File size limit: 10MB per file
  - Allowed MIME types: image/jpeg, image/png, image/jpg

  ## Photo Field Names (convention)
  - foto_vehiculo_frente
  - foto_vehiculo_costado_izquierdo
  - foto_vehiculo_costado_derecho
  - foto_vehiculo_trasera
  - foto_odometro
  - foto_vin
*/

-- Add prefolio columns to expedientes_servicio
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'expedientes_servicio' AND column_name = 'prefolio_realizado'
  ) THEN
    ALTER TABLE expedientes_servicio ADD COLUMN prefolio_realizado boolean DEFAULT false;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'expedientes_servicio' AND column_name = 'prefolio_vehiculo_texto'
  ) THEN
    ALTER TABLE expedientes_servicio ADD COLUMN prefolio_vehiculo_texto text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'expedientes_servicio' AND column_name = 'vehicle_numero_economico'
  ) THEN
    ALTER TABLE expedientes_servicio ADD COLUMN vehicle_numero_economico text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'expedientes_servicio' AND column_name = 'prefolio_modelo_dispositivo'
  ) THEN
    ALTER TABLE expedientes_servicio ADD COLUMN prefolio_modelo_dispositivo text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'expedientes_servicio' AND column_name = 'prefolio_imei_dispositivo'
  ) THEN
    ALTER TABLE expedientes_servicio ADD COLUMN prefolio_imei_dispositivo text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'expedientes_servicio' AND column_name = 'prefolio_telefono_sim'
  ) THEN
    ALTER TABLE expedientes_servicio ADD COLUMN prefolio_telefono_sim text;
  END IF;
END $$;

-- Create prefolio_fotos table
CREATE TABLE IF NOT EXISTS prefolio_fotos (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  expediente_id bigint NOT NULL REFERENCES expedientes_servicio(id) ON DELETE CASCADE,
  campo text NOT NULL,
  file_path text NOT NULL,
  created_at timestamptz DEFAULT now(),
  created_by uuid REFERENCES auth.users(id)
);

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_prefolio_fotos_expediente_id
  ON prefolio_fotos(expediente_id);

CREATE INDEX IF NOT EXISTS idx_prefolio_fotos_campo
  ON prefolio_fotos(campo);

CREATE INDEX IF NOT EXISTS idx_expedientes_servicio_prefolio_realizado
  ON expedientes_servicio(prefolio_realizado)
  WHERE prefolio_realizado = false;

-- Enable Row Level Security
ALTER TABLE prefolio_fotos ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (can be restricted later)
CREATE POLICY "Allow public read access to prefolio_fotos"
  ON prefolio_fotos
  FOR SELECT
  TO public
  USING (true);

CREATE POLICY "Allow public insert access to prefolio_fotos"
  ON prefolio_fotos
  FOR INSERT
  TO public
  WITH CHECK (true);

CREATE POLICY "Allow public update access to prefolio_fotos"
  ON prefolio_fotos
  FOR UPDATE
  TO public
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow public delete access to prefolio_fotos"
  ON prefolio_fotos
  FOR DELETE
  TO public
  USING (true);
